install.packages("formattable", repos = "http://cran.us.r-project.org")
install.packages("DiagrammeR", repos = "http://cran.us.r-project.org")
install.packages("data.tree", repos = "http://cran.us.r-project.org")
install.packages("remotes", repos = "http://cran.us.r-project.org")
remotes::install_github("gluc/ahp")
library(ahp)
library(data.tree)
library(formattable)
library(DiagrammeR)
ahpFile <- "/Users/aleksander/Documents/APU_2.ahp"
smAhp <- Load(ahpFile)
print(smAhp, filterFun = isNotLeaf)
Calculate(smAhp)
print(smAhp, "cena")
print(smAhp)